# Site settings
title: Jose Carapia
description: Profile
# baseurl:  # the subpath of your site, e.g. /blog
#url: "https://josecarapia.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jose Carapia
user_description:  Hi! I am Jose, I am fascinated by Math, Computers and the Physical laws of nature. I enjoy working with different technologies and would describe myself as a full stack developer.  
user_title: Software Developer
email: jose@josecarapia.com
twitter_username: lorem_ipsum
github_username:  josecarapia
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
